ROS Quickstart Guide
ultralytics/ultralytics pull request #13553
Opened 2024-06-13 08:40 UTC by ambitious-octopus

2024-06-13 09:00 UTC, ambitious-octopus commented
Docs gif:
![2024-06-1310-32-00-ezgif com-crop](https://github.com/ultralytics/ultralytics/assets/3855193/3caafc4a-0edd-4e5f-8dd1-37e30be70123)

2024-06-13 14:33 UTC, Burhan-Q requested changes, later dismissed
A few quick notes that I can add on minor edits. Overall looks good, but haven't _fully_ read the content yet and not sure I'll have the chance to test it out personally.

One other thing that you'll need to do is add an entry to `guides/index.md` as well.

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +keywords: Ultralytics, YOLO, object detection, deep learning, machine learning, guide, ROS, Robot Operating System, robotics, ROS Noetic, Python, Ubuntu, simulation, visualization, communication, mid
`Noetic Ninjemys,compatibility` add space after `,`

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +keywords: Ultralytics, YOLO, object detection, deep learning, machine learning, guide, ROS, Robot Operating System, robotics, ROS Noetic, Python, Ubuntu, simulation, visualization, communication, mid
not sure if compatibility, performance, stability are completely relevant here. Maybe add "autonomous vehicle", "AMV", "autonomous motorized vehicle", etc.

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Probably can remove extra line

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Single line between code blocks

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Probably can remove extra line

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Probably can remove extra line

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Probably can remove extra line

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Probably can remove extra line

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Probably can remove extra line

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Probably can remove extra line

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Remove extra line

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +
Probably can remove extra line

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +    Next, we subscribe to the `/camera/depth/points` topic to receive the point cloud message. We then convert the `sensor_msgs/PointCloud2` message into numpy arrays containing the XYZ coordinates a
Add line after code block

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +Consider a warehouse robot equipped with a camera and object detection model. Instead of sending large annotated images over the network, the robot can publish a list of detected classes as `std_msgs
> "box" "pallet" and "forklift"

add commas

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +    In this example, we use YOLO to segment an image and apply the extracted mask to segment the object in the depth image. This allows us to determine the distance of each pixel of the object of int
Consider linking to other docs pages when mentioning other tasks. Here you mention `segment` and `segmentation model`. With these you could do something like `[segment](../tasks/segment.md)` to link to another docs page. The most common ones to link to are the `modes`, `models`, and `tasks` but anything you can link to is great.

2024-06-13 14:33 UTC, Burhan-Q commented on docs/en/guides/ros-quickstart.md
> +    ### Step-by-Step Explanation
Consider using a numbered list for the steps.

2024-06-13 14:36 UTC, Burhan-Q commented
Also there is a [CI error](https://github.com/ultralytics/ultralytics/actions/runs/9497655681/job/26174728796#step:8:23) (not sure what the fix is here)

2024-06-13 14:39 UTC, ambitious-octopus commented on docs/mkdocs_github_authors.yaml
It's not me :smile:  , there is something writing this line, I think during the `mkdocs` build but I'm not sure.

2024-06-18 17:28 UTC, glenn-jocher commented on docs/en/guides/ros-quickstart.md
> +    ``` bash
let's delete this space

2024-06-18 17:28 UTC, glenn-jocher commented on docs/en/guides/ros-quickstart.md
> +    ``` bash
here also

2024-06-18 22:03 UTC, glenn-jocher commented
@ambitious-octopus I've fixed some missing formatting rules now in https://github.com/ultralytics/actions and now all the code snippet imports are being ordered correctly (and removed if unused) in https://github.com/ultralytics/ultralytics/pull/13553/commits/dcf23bfe0466f93171a4045804e9499f3d5dfb27.

2024-06-18 23:53 UTC, glenn-jocher approved these changes

2024-06-18 23:54 UTC, merged

2024-06-18 23:54 UTC, glenn-jocher commented
@ambitious-octopus PR merged! Nice work here :)