fix multiple windows opened when performing inference on image directory on Linux platform
ultralytics/ultralytics pull request #15429
Opened 2024-08-12 15:42 UTC by jugal-sheth

I have read the CLA Document and I sign the CLA

2024-08-12 15:49 UTC, jugal-sheth commented
I have read the CLA Document and I sign the CLA

2024-08-13 09:27 UTC, ambitious-octopus reviewed
Thanks @jugal-sheth for the PR. Can you clarify why this fix only affects Linux? Are windows automatically closing on Windows? Have you tested this behavior on Windows?

2024-08-13 14:55 UTC, jugal-sheth commented
@ambitious-octopus today I tested on windows and found same error so replaced cv2.destroyWindow(p) with cv2.destroyAllWindows()

2024-08-14 08:53 UTC, ambitious-octopus requested changes

2024-08-14 08:53 UTC, ambitious-octopus commented on ultralytics/engine/predictor.py
> +            cv2.destroyAllWindows()  # Destroys All cv windows can work on all platforms now
```suggestion
            cv2.destroyAllWindows() #Prevents opening multiple windows in image mode
```

2024-08-19 12:14 UTC, Burhan-Q commented
@ambitious-octopus I ran this on Windows. The result is not what I believe users will expect, as the image window opens for 300 ms and then immediately closes and might not be visible (it was under the VS Code window for me). This can be fixed by setting `cv2.waitKey(0)` instead of `cv2.waitKey(300)` however this will "appear" frozen as there is no prompt showing that the user can close the window using any key, however they can click the <kbd>x</kbd> on the image window, which will open the next image.

2024-08-19 12:27 UTC, jugal-sheth commented
@Burhan-Q  Thank you for your insights I was not sure if should change the default setting of 300 ms delay set in source code but, Yes definitely it can be set to 0 and user can change image by keypress that seems good idea 
the reason behind this PR was my system got frozen couple of times and required forced reboot when I ran code over large image directory 
If you think using cv2.waitKey(0) instead of cv2.waitKey(300) is good idea I can incorporate that in PR also for user to switch image we can use keyboard buttons and show prompt in image label window on top "Press n for next image" or something similar to that 

or we can add 1 more visualisation Arg may be called as 'delay' default set to 300 can consume any int and if 0 use n for next image 


Please comment your views and I will modify the code accordingly 

Kind regards

2025-06-20 00:23 UTC, closed without merging