Fix In and Out problems of Counter.count() issue for Line region
ultralytics/ultralytics pull request #16947
Opened 2024-10-15 23:55 UTC by Pn7Hao

object_counter.py

My friend and I discovered an issue with the 'In and Out' counting not functioning effectively in count.counter. We then found that the count_objects function was not calculating correctly and fixed it using the dot product. The following code:

Hope u guys understand and improve this ❤.

2024-10-15 23:56 UTC, UltralyticsAssistant commented
👋 Hello @Pn7Hao, thank you for submitting your `ultralytics/ultralytics` 🚀 PR! To ensure your updates to the object counting logic are seamlessly integrated, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Make sure your PR is up to date with the `ultralytics/ultralytics` `main` branch. If it's not, consider updating it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Confirm that all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any tests fail, please ensure they are addressed.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) if there are any new or modified features.
- ✅ **Add Tests**: If applicable, please include or update tests to ensure your changes are thoroughly validated, and confirm all tests pass.
- ✅ **Sign the CLA**: Make sure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by typing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Please limit your changes to the **minimum** necessary for your bug fix or feature addition. As Bruce Lee wisely noted, _"hack away the unessential."_

If you haven't included one, could you provide a minimum reproducible example (MRE) that demonstrates the initial issue with the `In and Out` counting logic? This will be immensely helpful in verifying the effectiveness of your changes.

For additional guidance, please check our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to leave a comment if you have any questions. Thank you for enhancing Ultralytics! 🚀🤖

⚠️ Please note that this is an automated response. An Ultralytics engineer will review and assist you with your PR soon.

2024-10-15 23:58 UTC, Pn7Hao commented
recheck

2024-10-15 23:58 UTC, Pn7Hao commented
I have read the CLA Document and I sign the CLA

2024-10-16 18:32 UTC, RizwanMunawar requested changes
Hi @Pn7Hao, Thank you for your PR! I’ve reviewed it. I have noticed that the changes were applied directly to each track, which I don't think make sense. Since the region counts are working properly. 

I have also performed testing with your changes and I am not getting correct counts using the `line` counter, the original code is displaying the counts correctly.😊

**On Left:** Existing Code
**On Right:** your proposed changes


<p align="center">
    <img src="https://github.com/user-attachments/assets/00bca07e-e1d4-4be5-8b37-fb4d1df05842" width="45%" alt="Image 1">
    <img src="https://github.com/user-attachments/assets/b8789b16-c9bb-4222-b926-b676abfc4a00" width="45%" alt="Image 2">
</p>

Thanks and Regards,
The Ultralytics Team!

2024-10-17 00:52 UTC, Pn7Hao commented
Hello @RizwanMunawar , let me explain: I understand your intention with `dx` and `dy`. You calculate from `box[0]` to the centroid, with objects to the left of the centroid being considered as Out—you're testing in a commercial area, which is also the case here—and conversely, objects to the right are In. However, I don’t believe this test case is accurate in a real commercial area where people can enter from the left, which would previously be counted as Out. The issue arises because the vector product of `dx` and `dy` is directed to the right, making it positive—in—and negative for the left—Out, which is an incorrect notion. I’ll provide some test cases for your understanding; the drive link is below.

Regarding my idea: use the previous point and the current point to create a directional vector, then perform a dot product with the line's vector to determine the orientation along the coordinate axis. If the formula at `d` is negative, it indicates Out, meaning the resultant vector has crossed and does not conform to the coordinate axis. Conversely, a positive value indicates In.

Some drawbacks of this basic idea are: If the object is not moving, there won’t be a previous point to calculate the vector, nor can we consider whether the objects have crossed the line yet. Additionally, because it involves vector lines, objects outside may also be counted in the object_counter function.

Test cases fail: `https://drive.google.com/drive/folders/1TJkxlgYygwdo-GLn960v1u-zlVX0RkXT`

I hope that you understand and improve my idea cases.

2024-10-17 00:57 UTC, Pn7Hao commented
This idea is based on evaluating which hemisphere the resultant vector belongs to and whether that hemisphere aligns with the coordinate axis, with a resultant of 0 indicating a stop at the line.

2024-10-17 01:15 UTC, Pn7Hao commented
For test case:
+
green dot: centroid point of region line
red dot: prev_position
black dots: track_line
+
dx: -25419.541015625, dy: 1212.135986328125
prev_position: (tensor(767.1521), tensor(549.5820))
box: tensor([635.3408, 423.0811])
centroid: POINT (960 540)
+ 
box[0] - prev_position[0] = negative
centroid.x - prev_position[0] = positive

-> dx negative -> out_count increase

This take time for me findout this problem hrere 😉
As I mentioned, in and out should depend on the movement vector of the previous point and the line axis, not the region.

![out2](https://github.com/user-attachments/assets/ae56f175-c4d7-44f3-97cd-9b8dbd90dcd6)
![out1](https://github.com/user-attachments/assets/4229e877-e044-4469-8bd6-de671decc3f0)

2024-10-17 08:10 UTC, glenn-jocher commented
Thank you for your detailed explanation. It seems like the issue lies in the calculation of the movement vector. Your suggestion to use the previous and current points to determine direction is insightful. We'll review the test cases and consider your approach for improving the accuracy of the in and out counts. If you have further insights, feel free to share them.

2024-10-17 16:55 UTC, RizwanMunawar commented
@Pn7Hao I get what you're saying. Let's test it on different use cases to see if we can resolve the issue without modifying the codebase. I believe your PR is valid, but I'll need some time to test it over the next few days. If everything checks out, we can move forward with merging the PR :)

2024-10-17 22:07 UTC, Pn7Hao commented
Hi @RizwanMunawar, i know my idea still has many shortcomings, and I am also checking the remaining cases. Do you think besides testing the movement of people in the shopping mall, there could be anything else possible to test? I will help you test and improve my shortcomings.

2024-10-18 20:11 UTC, Pn7Hao commented
Hi @RizwanMunawar , after we modified the code for visualization, as I mentioned, all movements in the Left side of the `centroid` are considered **Out**, while all movements in the Right side of the `centroid` are considered **In**. This is not aligned with the criteria for **In and Out** area set according to the straight line. The code remains the same, but we will include a video testing your code and our proposal.

drive: `[2 videos](https://drive.google.com/drive/folders/1kM0NIYquGAij1f36xr9wsYEKE6MQbD4i?usp=sharing)` 
Note: `output.mp4` is original code, `output2.mp4` is pull request
origin data: `[data](https://www.youtube.com/watch?v=WvhYuDvH17I)`

2024-10-21 07:49 UTC, RizwanMunawar commented
Hey @Pn7Hao! Could you try object counting using region and see if it works well for your use case? If everything looks good, I can go ahead and disable the line counting support since it might not fit every scenario. The idea of adding the dot product makes sense, but I’m not sure it would work across all use cases. Let me know your thoughts! Thanks

2024-10-21 19:07 UTC, Pn7Hao commented
Hi @RizwanMunawar,
In my observation and experiments, the In and Out here do not depend on the direction of movement and the centroid—similar to the Line issue.

Objects entering the **region from the left** are counted as **Out**. Objects entering the **region from the right** are counted as **In**. This includes all cases of movement from top to bottom and bottom to top.

I believe the issue here is that an object is counted as In when it is within the region and Out when it is outside the region.

I suggest that if it’s a Line, we should divide it into two areas. If it’s a region, we need to adjust the function—I am currently researching how to do this.

2025-06-19 00:24 UTC, closed without merging