Revise docs for `pretrained` arg
ultralytics/ultralytics pull request #17248
Opened 2024-10-29 17:31 UTC by Y-T-G

Closes #17246 

I think the argument itself should be changed functionally because it's inconsistent behavior, doing two different things.

For classify, it decides whether to use pretrained weights besides also accepting `str` argument which has the same behavior as other tasks:
https://github.com/ultralytics/ultralytics/blob/aabd0136ec40223cf423847635a2a4de95bba63d/ultralytics/models/yolo/classify/train.py#L53-L54

Not sure when this is used, if at all:
https://github.com/ultralytics/ultralytics/blob/aabd0136ec40223cf423847635a2a4de95bba63d/ultralytics/models/yolo/classify/train.py#L65-L69

For other tasks, it only has an effect if it is a path:
https://github.com/ultralytics/ultralytics/blob/aabd0136ec40223cf423847635a2a4de95bba63d/ultralytics/engine/trainer.py#L575-L576

2024-10-29 17:32 UTC, UltralyticsAssistant commented
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to help guide you through the contribution process, and an Ultralytics engineer will also follow up soon to assist you further.

To ensure your PR integrates smoothly, kindly review the checklist below:

- ✅ **Define a Purpose**: Clearly explain the purpose of the changes in your PR description and reference any [relevant issues](https://github.com/ultralytics/ultralytics/issues) it addresses. Be sure that your commit messages are clear and aligned with the project's guidelines.
- ✅ **Synchronize with Source**: Confirm your PR is up-to-date with the `main` branch of the `ultralytics/ultralytics` repository. If necessary, update it by clicking 'Update branch' or by executing `git pull` and `git merge main` on your local setup.
- ✅ **Ensure CI Checks Pass**: Make sure all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks pass successfully. Should any issues arise, please address them.
- ✅ **Update Documentation**: Where applicable, update the [documentation](https://docs.ultralytics.com) corresponding to your changes.
- ✅ **Add Tests**: Include or adapt tests if necessary to reflect your changes, ensuring all tests conclude successfully.
- ✅ **Sign the CLA**: If this is your first contribution to an Ultralytics project, please sign the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by stating "I have read the CLA Document and I sign the CLA" in a comment.
- ✅ **Minimize Changes**: Aim to keep your changes to the essential modifications required for your proposed feature or bug fix. _"Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away."_ — Antoine de Saint-Exupéry

For a more thorough guide, refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions or need further clarification, feel free to comment below. Thank you for your contributions to Ultralytics! 🚀

P.S. 😊 If your PR includes a bug report, please ensure you provide a Minimum Reproducible Example (MRE) to better aid our analysis and resolution.

2024-10-29 18:40 UTC, Y-T-G commented
The behavior currently is:
```
if pretrained is False:
  if the task is classify:
    if the model passed using model argument is a pretrained checkpoint:
      reset weights
    else:
      no effect (weights are still reset but effectively doesn't matter since the original model is not pretrained)
  else:
    no effect
elif pretrained is Path and the task is any:
  load the weights from pretrained path
```

2024-10-29 21:56 UTC, glenn-jocher commented
@Y-T-G yes I agree, behavior should be consistent between Classify and other tasks. We want `pretrained` to be able to be used in conjunction with any *.pt file to "reset" those weights to an untrained state, i.e.

`yolo train model=yolo11n.pt pretrained=False` should be the same as `yolo train model=yolo11n.yaml`.

Maybe we should take the opportunity to apply these changes in this PR?

2024-10-29 22:14 UTC, Y-T-G commented
@glenn-jocher Sure, that's a good idea

2024-11-03 10:34 UTC, Y-T-G commented
@glenn-jocher I updated `pretrained` to behave the same for all tasks. If it's False, it should start training from scratch even if the passed model is `.pt`

2024-12-02 10:45 UTC, fcakyon requested changes
https://github.com/ultralytics/ultralytics/pull/17248/files#r1865627553

2025-01-14 23:09 UTC, closed without merging