Sesame Plant Dataset
ultralytics/ultralytics pull request #17618
Opened 2024-11-18 21:26 UTC by esssyjr

2024-11-18 21:27 UTC, UltralyticsAssistant commented
👋 Hello @esssyjr, thank you for your contribution to the `ultralytics/ultralytics` repository with this exciting new dataset addition! 🌿📊 This automated response will guide you through ensuring your PR is ready for review. An Ultralytics engineer will also assist you soon.

- ✅ **Define a Purpose**: You've done a great job outlining the purpose of your contribution and its potential impact on agricultural applications. Remember to link any [relevant issues](https://github.com/ultralytics/ultralytics/issues) if applicable.

- ✅ **Synchronize with Source**: Ensure your branch is up to date with the `main` branch of the ultralytics repository. If needed, click 'Update branch' or use `git pull` followed by `git merge main` locally.

- ✅ **Ensure CI Checks Pass**: Please verify that all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, investigate and resolve the issues.

- 🚀 **Update Documentation**: You've included a detailed README within your contribution, which is excellent! Double-check to ensure it aligns with the style and format of the existing [documentation](https://docs.ultralytics.com).

- ✅ **Add Tests**: While adding datasets typically doesn't require tests in the conventional sense, consider including a simple verification script that checks the integrity or basic usability of the dataset with Ultralytics models.

- ✅ **Sign the CLA**: If this is your first contribution to Ultralytics, ensure you've signed the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/). You can do this by adding a comment stating, "I have read the CLA Document and I sign the CLA."

- ✅ **Minimize Changes**: Your PR appears to add only the necessary files for the Sesame Plant Dataset, which is ideal. Remember, _"Hack away the unessential"._ — Bruce Lee

For more details, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don't hesitate to comment here if you have any questions. Thank you for your valuable contribution to Ultralytics! 🌟💪

2024-11-18 21:47 UTC, esssyjr commented
I have read the CLA Document and I sign the CLA

2024-11-19 10:51 UTC, RizwanMunawar commented
@esssyjr Hi, thank you for the PR! It’s great that you’ve uploaded the dataset zip file. However, please ensure you follow the structure outlined in our [documentation](https://docs.ultralytics.com/datasets/#contribute-new-datasets). This will make your PR clearer to everyone and facilitate an easier merge. 🙂

Looking forward to new changes from your side.

Thanks, 
The Ultralytics Team :)

2024-11-22 16:22 UTC, ambitious-octopus requested changes
Hey @esssyjr, thanks for the PR but this is not the right way to add a new dataset. 
The correct way is to create a `.yaml `file like in [this guide](https://docs.ultralytics.com/datasets/). You should also create a page in the documentation (./docs).

2024-11-22 19:00 UTC, esssyjr commented
> Hey @esssyjr, thanks for the PR but this is not the right way to add a new dataset. The correct way is to create a `.yaml `file like in [this guide](https://docs.ultralytics.com/datasets/). You should also create a page in the documentation (./docs).
Thank you for your reply. I included the `.yaml` file in the zip file. From your response, I understand that everything I did was correct except for the `.yaml` file, which I will move to the root directory and `README.md` file should be placed in the `./docs` directory, correct?

2024-11-25 03:17 UTC, glenn-jocher commented
Thank you for following up, @esssyjr. That’s correct—please move the `.yaml` file to the root directory and add the `README.md` within the `./docs` directory. This will align your PR with the correct format outlined in our [dataset contribution guide](https://docs.ultralytics.com/datasets/). Let us know if you have any further questions!

2024-11-26 06:33 UTC, esssyjr commented
> Thank you for following up, @esssyjr. That’s correct—please move the `.yaml` file to the root directory and add the `README.md` within the `./docs` directory. This will align your PR with the correct format outlined in our [dataset contribution guide](https://docs.ultralytics.com/datasets/). Let us know if you have any further questions!

I’ve made the requested changes and ensured they align with the provided guidelines. Thank you for the valuable feedback throughout this process. I look forward to your final review.

2024-11-26 11:24 UTC, glenn-jocher commented
Thank you for making the updates promptly, @esssyjr. We’ll review your changes and provide feedback or approval shortly. Thank you for your meticulous work and contribution!

2024-11-26 11:50 UTC, ambitious-octopus requested changes
Hey @esssyjr, there are still some problems, please follow [this guide](https://docs.ultralytics.com/datasets/#steps-to-contribute-a-new-dataset).

2024-11-26 11:55 UTC, ambitious-octopus requested changes
@esssyjr The dataset seems promising, but there are a few issues to address:

1. Many images appear to be duplicated.
2. It seems the dataset already has augmentation applied, which might limit its usability for certain tasks.
3. The file names are not very informative; consider using a more systematic naming convention, such as sequential numbering (e.g., 01.jpg, 02.jpg, etc.), similar to the COCO dataset format.

Out of curiosity, did you create this dataset yourself?

2024-11-26 15:31 UTC, glenn-jocher commented
Thank you for your response and for clarifying. Yes, removing augmented images is recommended, as augmentations are typically best applied dynamically during training. A more systematic naming convention will also improve clarity and usability. Adding more original images, if possible, would enhance the dataset's quality and robustness. Once these updates are made, ensure the dataset structure aligns with YOLO guidelines, as described in the [documentation](https://docs.ultralytics.com/datasets/). Let us know if you need further assistance!

2024-11-28 12:19 UTC, Skillnoob commented
@esssyjr Your dataset is not very big and you shouldn't have augmented images in your dataset. Your dataset should at least achieve the minimum requirements described [here](https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/), otherwise it will not be very useful.

2024-11-29 07:43 UTC, esssyjr commented
> Thank you for your response and for clarifying. Yes, removing augmented images is recommended, as augmentations are typically best applied dynamically during training. A more systematic naming convention will also improve clarity and usability. Adding more original images, if possible, would enhance the dataset's quality and robustness. Once these updates are made, ensure the dataset structure aligns with YOLO guidelines, as described in the [documentation](https://docs.ultralytics.com/datasets/). Let us know if you need further assistance!

Thank you very much, I will make the necessary changes and submit again. I hope I am not giving tough time.

2024-11-29 07:48 UTC, esssyjr commented
> @esssyjr Your dataset is not very big and you shouldn't have augmented images in your dataset. Your dataset should at least achieve the minimum requirements described [here](https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/), otherwise it will not be very useful.

Thanks for the response. 
Sure, I understand the fact that I cant use augmented images. But regarding the dataset size, I came across the SIGNATURE dataset which is 143 images, a number lower than mine. Also, for my dataset there use to be instances where 20+ of the class can be found in one image.

2024-11-30 07:47 UTC, glenn-jocher commented
Thank you for clarifying. While smaller datasets like SIGNATURE can work in specific cases, achieving robust performance typically requires adhering to the recommended dataset size and variety outlined [here](https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/). High instance counts per image can help but don’t fully substitute for diverse, well-labeled data. Expanding your dataset and increasing its variability will better ensure strong and reliable model performance. Let us know if you need further guidance!

2025-06-19 00:24 UTC, closed without merging