Add support for loading and inferencing on aws-neuron and aws-neuronx
ultralytics/ultralytics pull request #18199
Opened 2024-12-12 09:46 UTC by takipipo

2024-12-12 09:47 UTC, takipipo commented
I have read the CLA Document and I sign the CLA

2024-12-13 17:15 UTC, ambitious-octopus requested changes
Hey @takipipo , the AWS-Neuron inference integration you're working on looks very promising. Thank you for your effort and contributions! 
That said, the PR requires some adjustments and cleanup to align with our codebase.

1. Duplicate Code: You've introduced a new exporter.py and autobackend.py, which results in a lot of duplicate code. Instead of creating new files, please integrate your changes into the existing exporter.py and autobackend.py to maintain consistency and reduce redundancy.

2. NeuronYOLO Model: There’s no need to create a separate NeuronYOLO model for this integration. Both inference and export functionality should be handled within autobackend.py and exporter.py as part of the existing framework.

Unfortunately, I’m unable to test your PR in its current state. Once you've made these changes I’ll take another look.

Thanks again for your contributions!

2024-12-13 17:15 UTC, ambitious-octopus commented on ultralytics/cfg/__init__.py
Why did you simplify the docstrings here?

2024-12-13 17:15 UTC, ambitious-octopus commented on ultralytics/engine/exporter.py
> +        """YOLOv8 NCNN export using PNNX https://github.com/pnnx/pnnx."""
```suggestion
        """YOLO NCNN export using PNNX https://github.com/pnnx/pnnx."""
```

2024-12-15 23:11 UTC, takipipo commented
Will be taking a look on this PR this week
- [ ] Fix code duplication

2024-12-16 07:20 UTC, glenn-jocher commented
@takipipo thank you for your update! Please let us know if you have any questions or need assistance as you work on this.

2024-12-19 14:18 UTC, takipipo commented
@ambitious-octopus Thank you for your review and suggestions. Since ubuntu is an anonymous code committer and will not be able to sign the CLA, should I open the new PR and fix this?

2024-12-19 14:39 UTC, takipipo commented
I've made the change and will be merging to the `wisesight:main` after the review has been made in https://github.com/wisesight/ultralytics/pull/9 @glenn-jocher @ambitious-octopus

2024-12-20 03:42 UTC, glenn-jocher commented
@takipipo thank you for the update! Please ensure all necessary reviews are completed, and feel free to reach out if you need any further assistance.

2025-06-19 00:24 UTC, closed without merging