Add support for `is_jetson()` inside Docker environments
ultralytics/ultralytics pull request #18449
Opened 2024-12-30 04:45 UTC by lakshanthad

@glenn-jocher 
Currently we are using `/proc/device-tree/model` to detect NVIDIA Jetson and this is not accessible inside Docker environments. In order to expose this directory to Docker, we need to run Docker in `privileged` mode (if we do this, we simply need to change the docker run commands in the doc page):

```bash
sudo docker run -it --privileged xxxx
```

However, according to [Docker documentation](https://docs.docker.com/security/faqs/containers/), using privileged mode is not recommended for production environments as it exposes the entire host system to the container, effectively giving the container unrestricted access to the host.

The approach in this PR is an idea to address this issue.

2024-12-30 04:46 UTC, UltralyticsAssistant commented
👋 Hello @lakshanthad, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and ensure your commit messages are clear and concise.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics Continuous Integration (CI) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant documentation for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our Contributor License Agreement (CLA) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

An Ultralytics engineer will review your PR soon and provide additional feedback if necessary. Thank you for contributing to Ultralytics! 🚀

2024-12-30 09:54 UTC, ambitious-octopus reviewed
@lakshanthad If you don't want to introduce an env variable you can try something like this:

```bash
 # create a file
echo "hello" > test.txt
# Run container a map a single file.
docker run -it --mount type=bind,source=./test.txt,target=/var/test.txt ubuntu:20.04 bash
```

This command maps a single file into the container.

2024-12-30 14:36 UTC, glenn-jocher commented
@lakshanthad environment variables are defined in Docker images here:
https://github.com/ultralytics/ultralytics/blob/564d3e5efdd1981b826a2241ccc7ab86615f0433/docker/Dockerfile-jetson-jetpack4#L8-L11

2024-12-30 14:37 UTC, glenn-jocher requested changes
Environment variable definition in Docker images should be handled directly in the Dockerfile

https://github.com/ultralytics/ultralytics/blob/564d3e5efdd1981b826a2241ccc7ab86615f0433/docker/Dockerfile-jetson-jetpack4#L8-L11

2025-01-02 09:57 UTC, lakshanthad commented
@glenn-jocher 

After further research, it seems using `platform.release()` is the most suitable approach without using additional environment variables and `--privileged` arguments.

Output for both Raspberry Pi and NVIDIA Jetson are as follows:

```sh
# Raspberry Pi
>>> platform.release()
'6.6.51+rpt-rpi-2712'
```

```sh
# NVIDIA Jetson
>>> platform.release()
'5.10.120-tegra'
```

2025-01-02 20:28 UTC, glenn-jocher approved these changes

2025-01-02 20:34 UTC, merged

2025-01-02 20:44 UTC, glenn-jocher commented
@lakshanthad PR merged!