Improve Object Counter by class
ultralytics/ultralytics pull request #8679
Opened 2024-03-05 10:42 UTC by ethyljoybadiang

It counts each class' incoming and out-going on each class of the model. Attached is a short demo of the feature. It can be used in intelligent traffic systems, entrances and exits of establishments, and many more.

Uploading PoC.mp4…

I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced object counting capabilities for two-way directions and individual object tracking.

### 📊 Key Changes
- Imported `copy` module to handle deep copying of dictionaries.
- Added individual object counting with separate incoming and outgoing counting for two-way counting regions.
- Created additional dictionaries (`incoming`, `outgoing`, `two_way`, `object_list`) to track counts per object type.
- Introduced new methods (`get_incoming`, `get_outgoing`, `get_in_counts`, `get_out_counts`, `get_two_way`) for accessing count information.
- Added a `greet` method showcasing successful inheritance (likely for testing or demonstration).
- Implemented an `inherit_dictionary` method to initialize the counting dictionaries based on provided `object_list`.
- Developed a new method, `start_twocounts`, to combine the original start counting with two-way directional counting.

### 🎯 Purpose & Impact
- **Improved granularity**: Able to count objects moving in both directions and categorize counts per object type, enhancing data richness.
- **Better state management**: Through deep copying and new methods, the object state is reliably managed and accessed, ensuring accurate and consistent counting.
- **Increased flexibility for future extensions**: The modular design of counting and new methods facilitates easy maintenance and potential feature additions.

2024-03-05 17:30 UTC, glenn-jocher commented
@ethyljoybadiang thanks for the PR! We have an earlier object counting improvement PR in https://github.com/ultralytics/ultralytics/pull/8648 that we will merge first. Please take a look at this PR and see if it meets your requirements.

2024-03-05 23:08 UTC, ethyljoybadiang commented
I have read the CLA Document and I sign the CLA

On Tue, Mar 5, 2024, 6:42 PM github-actions[bot] ***@***.***>
wrote:

> *CLA Assistant Lite bot:*
> Thank you for your submission, we really appreciate it. Like many
> open-source projects, we ask that you sign our Contributor License
> Agreement <https://docs.ultralytics.com/help/CLA> before we can accept
> your contribution. You can sign the CLA by just posting a Pull Request
> Comment same as the below format.
> ------------------------------
>
> I have read the CLA Document and I sign the CLA
> ------------------------------
>
> You can retrigger this bot by commenting *recheck* in this Pull Request
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ultralytics/ultralytics/pull/8679#issuecomment-1978465117>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A77JEGXLP52BFBCO74GA42LYWWOSFAVCNFSM6AAAAABEG4BY4GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZYGQ3DKMJRG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-06 02:08 UTC, ethyljoybadiang commented
> @ethyljoybadiang thanks for the PR! We have an earlier object counting improvement PR in #8648 that we will merge first. Please take a look at this PR and see if it meets your requirements.

Good day. That 

> @ethyljoybadiang thanks for the PR! We have an earlier object counting improvement PR in #8648 that we will merge first. Please take a look at this PR and see if it meets your requirements.

I have seen the PR, it is not the same as mine. Mine focuses on the counting of each class which solves the question," How many persons entered?", and "How many cars went out?".

2024-03-06 04:21 UTC, glenn-jocher commented
@ethyljoybadiang hello! 😊 Thank you for checking out the other PR and for your clarification. It sounds like your contribution adds a valuable dimension to object counting by focusing on detailed class-specific counts for both incoming and outgoing objects. This indeed addresses more specific questions that could be incredibly useful in various applications. 

We appreciate the unique perspective your PR brings. Let's keep it open for further review and consideration after merging the initial improvements. Your work on enhancing the granularity of object counting is highly valued! 

If there are any specific aspects of your implementation you'd like to highlight or discuss further, please feel free to share. 🚀

2024-03-06 04:54 UTC, ethyljoybadiang commented
> @ethyljoybadiang hello! 😊 Thank you for checking out the other PR and for your clarification. It sounds like your contribution adds a valuable dimension to object counting by focusing on detailed class-specific counts for both incoming and outgoing objects. This indeed addresses more specific questions that could be incredibly useful in various applications.
> 
> We appreciate the unique perspective your PR brings. Let's keep it open for further review and consideration after merging the initial improvements. Your work on enhancing the granularity of object counting is highly valued!
> 
> If there are any specific aspects of your implementation you'd like to highlight or discuss further, please feel free to share. 🚀

Would it be okay to include a sample code of the demo video I shared? If that is okay with you though.

2024-03-06 05:04 UTC, ethyljoybadiang commented
Here is a demo video of the added feature.
https://github.com/ultralytics/ultralytics/assets/134124058/8451fffa-f688-48fc-b40e-3e29f59fc751

2024-03-06 09:32 UTC, glenn-jocher commented
@ethyljoybadiang understood thank you! Can you please resolve the conflicts?
<img width="933" alt="Screenshot 2024-03-06 at 10 31 51" src="https://github.com/ultralytics/ultralytics/assets/26833433/2ad7fa9b-b675-4f8e-9293-ec30f2349e23">

Once that's done @RizwanMunawar can review!

2024-03-06 17:37 UTC, Burhan-Q reviewed
Comments are recommendations or suggestions that _could_ help the chances your changes are accepted. There's no assurance changes will be accepted, even after making updates based on some or all of my recommendations.

2024-03-06 17:37 UTC, Burhan-Q commented on ultralytics/solutions/object_counter.py
> +                        """Updates the class' incoming value."""
Use `#` for inline comments instead of `"""` which should be for multiline comments

2024-03-06 17:37 UTC, Burhan-Q commented on ultralytics/solutions/object_counter.py
> +                        """Updates the class' outgoing value."""
Use `#`

2024-03-06 17:37 UTC, Burhan-Q commented on ultralytics/solutions/object_counter.py
> +                            """Updates the class' incoming value."""
Use `#`

2024-03-06 17:37 UTC, Burhan-Q commented on ultralytics/solutions/object_counter.py
> +                            """Updates the class' outgoing value."""
Use `#`

2024-03-06 17:37 UTC, Burhan-Q commented on ultralytics/solutions/object_counter.py
> +        return self.two_way
Make sure to add docstrings. Would be nice to add return annotations, for example `def get_incoming(self) -> dict[int]:`

2024-03-06 17:37 UTC, Burhan-Q commented on ultralytics/solutions/object_counter.py
> +    def greet(self, name):
1. `"""` should also be indented
2. Docstrings should follow the Google-style docstring [see here](https://docs.ultralytics.com/help/contributing/#google-style-docstrings)
3. Docstring should start on the line immediately after the function/method definition, move up to `L305`
4. Consider rewriting or revising the docstring description, it's difficult to read and may not be clear to others, consider using an LLM to help summarize your code

2024-03-06 17:37 UTC, Burhan-Q commented on ultralytics/solutions/object_counter.py
> +    def inherit_dictionary(self, object_list):
Add docstring, following all previous comments.

2024-03-06 17:37 UTC, Burhan-Q commented on ultralytics/solutions/object_counter.py
> +    def inherit_dictionary(self, object_list):
The argument `object_list` may cause users to think a `list` object should be passed, although it appears it probably _should_ be a `dict` object. Consider type hints, renaming, and/or type checking/assertion.

2024-03-07 03:58 UTC, ImranAhsan15 commented
This additional feature is vary useful in transportation sector and urban planning. I have to know about the directional vehicle type and counting as an urban planner.

2024-03-07 05:09 UTC, ethyljoybadiang commented
I have read the CLA Document and I sign the CLA

2024-03-07 05:11 UTC, ethyljoybadiang commented
> This additional feature is vary useful in transportation sector and urban planning. I have to know about the directional vehicle type and counting as an urban planner.

Thank you. May my addition be helpful to you and your use-case. :)

2024-03-07 05:43 UTC, ImranAhsan15 commented
> > This additional feature is vary useful in transportation sector and urban planning. I have to know about the directional vehicle type and counting as an urban planner.
> 
> Thank you. May my addition be helpful to you and your use-case. :)

yes ..it is very useful for me to make decision

2024-03-07 15:29 UTC, ImranAhsan15 commented
> @ImranAhsan15 i'm thrilled to hear that! 😊 If you need further assistance or have any questions as you integrate this feature into your projects, don't hesitate to reach out. Happy planning!

@glenn-jocher ultralytics is doing great. We need such a program that can be helpful in transportation engineering. But in this sector direction of traffic flow and class based counting and direction is very important exactly same @ethyljoybadiang has shown. Only counting or tracking can not be used in transportation engineering. So it is highly requested to incorporate this feature for the community with proper documentation or guideline.  For your kind information, what we, the transportation engineers are looking for as given bellow with video link-

https://www.youtube.com/watch?v=SZFtHPYgUzY

Good wishes for you and your great team.

2024-03-07 18:12 UTC, glenn-jocher commented
@ImranAhsan15, thank you for the kind words and for sharing your insights! 🚀 We understand the importance of directional traffic flow and class-based counting for transportation engineering. The feature demonstrated by @ethyljoybadiang indeed adds significant value in this context.

We're always looking to enhance our models to better serve various sectors, including transportation engineering. Incorporating such features with comprehensive documentation is on our radar. Meanwhile, the video you shared offers great context, and we'll certainly consider how best to integrate and document similar functionalities for broader use.

Stay tuned for updates, and feel free to contribute or suggest further enhancements. Your feedback is invaluable in helping us improve. 🛣️

2024-03-07 18:39 UTC, glenn-jocher commented
@Burhan-Q @RizwanMunawar hey guys, can you please review the updates and let me know if this is good to merge?

2024-03-07 20:06 UTC, Burhan-Q approved these changes
Suggestions I made have been resolved. I have not tested anything here, only reviewed the styling and docstrings.

2024-03-08 07:05 UTC, ethyljoybadiang reviewed
I have read the CLA Document and I sign the CLA

2024-03-08 07:55 UTC, RizwanMunawar requested changes
@ethyljoybadiang, appreciate the PR! After reviewing the code, it seems you've made modifications to internal functions for displaying `in_counts` and `out_counts` classwise, which is an intriguing and fantastic feature for analytics. 

However, I have concerns about the efficiency of using `deepcopy`, as it will extremely slow the object counting process. I suggest creating a single function to store counting information and later dumping it in `json` format for user-friendly analytics. Also please make sure to resolve the code conflicts first! Thanks

i.e
``` python
def store_data():
    ''''
```

@glenn-jocher @Burhan-Q, the PR looks good in terms of code format, but the logic seems unclear to me right now. Just a heads up, we currently support `in` and `out` counts. Users can access them through the provided link; however, classwise counts are not supported yet, which is the aim of this PR!

``` python
from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2

model = YOLO("yolov8n.pt")
cap = cv2.VideoCapture("path/to/video/file.mp4")
assert cap.isOpened(), "Error reading video file"

# Define region points
region_points = [(20, 400), (1080, 404), (1080, 360), (20, 360)]

# Init Object Counter
counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=region_points,
                 classes_names=model.names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    tracks = model.track(im0, persist=True, show=False)

    im0 = counter.start_counting(im0, tracks)
    print("In Counts", counter.in_counts)
    print("Out Counts", counter.out_counts)

cap.release()
cv2.destroyAllWindows()
```

Thanks
Ultralytics Team!

2024-03-08 08:04 UTC, ethyljoybadiang commented
> @ethyljoybadiang, appreciate the PR! After reviewing the code, it seems you've made modifications to internal functions for displaying `in_counts` and `out_counts` classwise, which is an intriguing and fantastic feature for analytics.
> 
> However, I have concerns about the efficiency of using `deepcopy`, as it will extremely slow the object counting process. I suggest creating a single function to store counting information and later dumping it in `json` format for user-friendly analytics. Also please make sure to resolve the code conflicts first! Thanks
> 
> i.e
> 
> ```python
> def store_data():
>     ''''
> ```
> 
> @glenn-jocher @Burhan-Q, the PR looks good in terms of code format, but the logic seems unclear to me right now. Just a heads up, we currently support `in` and `out` counts. Users can access them through the provided link; however, classwise counts are not supported yet, which is the aim of this PR!
> 
> ```python
> from ultralytics import YOLO
> from ultralytics.solutions import object_counter
> import cv2
> 
> model = YOLO("yolov8n.pt")
> cap = cv2.VideoCapture("path/to/video/file.mp4")
> assert cap.isOpened(), "Error reading video file"
> 
> # Define region points
> region_points = [(20, 400), (1080, 404), (1080, 360), (20, 360)]
> 
> # Init Object Counter
> counter = object_counter.ObjectCounter()
> counter.set_args(view_img=True,
>                  reg_pts=region_points,
>                  classes_names=model.names,
>                  draw_tracks=True)
> 
> while cap.isOpened():
>     success, im0 = cap.read()
>     if not success:
>         print("Video frame is empty or video processing has been successfully completed.")
>         break
>     tracks = model.track(im0, persist=True, show=False)
> 
>     im0 = counter.start_counting(im0, tracks)
>     print("In Counts", counter.in_counts)
>     print("Out Counts", counter.out_counts)
> 
> cap.release()
> cv2.destroyAllWindows()
> ```
> 
> Thanks Ultralytics Team!

Okay, will try that. Thank you!! I was just lazy so I used deepcopy.

2024-03-08 16:10 UTC, glenn-jocher commented
Hey @ethyljoybadiang, thanks for your quick response and openness to feedback! 😄 Your approach to enhancing the analytics capabilities is truly appreciated. I understand the convenience of `deepcopy`, but optimizing for efficiency will definitely make a big difference for users, especially in real-time applications. Your willingness to refine the feature is what makes this community so great. If you need any assistance or have questions while making adjustments, feel free to reach out. Looking forward to seeing the updated PR! 🚀

2024-03-08 23:15 UTC, ImranAhsan15 commented
@glenn-jocher hi. Hope you are well. I am facing an issue about changing the Line. When i am going to move the line downward the entire video stopped running after some time.

2024-03-13 05:30 UTC, ethyljoybadiang commented
I have read the CLA Document and I sign the CLA

2024-03-13 09:52 UTC, ethyljoybadiang reviewed
I have read the CLA Document and I sign the CLA

2024-09-20 07:54 UTC, RizwanMunawar commented
Hi @ethyljoybadiang, Thank you for your pull request. However, we haven’t seen any updates on it for a couple of months. I also have some concerns regarding the use of `deepcopy`. With recent updates, you can now directly access `classwise_counts` without significant changes.

For now, we’ll be closing this PR. If you’d like to contribute new features to Ultralytics Solutions, feel free to submit a new one. We’d be happy to review it.

We are looking forward to your future contributions.

cc: @ambitious-octopus 

Best regards,
The Ultralytics Team

2024-09-20 07:54 UTC, closed without merging