Patch based inference documentation
ultralytics/ultralytics pull request #9387
Opened 2024-03-28 18:56 UTC by Koldim2001

Good day, we have contacted you regarding the documentation of a new library that will allow users to better interact with ultralytics models (here is the link to the discussions section - https://github.com/orgs/ultralytics/discussions/9381). I have tried to describe the interaction with my library as detailed and understandable as possible, and I hope this will allow it to be added to the official documentation. I would be very grateful!

 _I have read the CLA Document and I hereby sign the CLA_

2024-03-28 19:01 UTC, Koldim2001 commented
I have read the CLA Document and I sign the CLA

2024-03-28 23:08 UTC, Burhan-Q commented
@Koldim2001 hey thanks for your write up. I'll definitely take a look at this when I have a chance, but you should update the license on your repository. Any code using `ultralytics` will need to use AGPL-3.0 and presently you have the MIT License for your repo. This violates the AGPL-3.0 terms as it stands, so I think it would be good to make sure your repo is properly licensed. You can just copy [this file](https://github.com/ultralytics/ultralytics/blob/main/LICENSE) and replace your existing `LICENSE.txt`

2024-03-29 08:50 UTC, Koldim2001 commented
@Burhan-Q Thank you very much for informing me. I have just made changes to the package license on the pypi and github sites

2024-03-31 23:09 UTC, Burhan-Q requested changes
In general the documentation guide needs a lot of work to be published. That's without even evaluating the package that's being discussed. It's definitely a good first effort and there are a lot of things I know are not going to be obvious, but that's why I took the time to write my review here for you. A couple overall notes:

1. The main body needs work. It's better to break up explanations and smaller snippets of code. Small blocks of code, followed by explanations will flow a lot easier; see other guide examples for reference.

2. Make sure to optimize all images and that no source image `width` or `height` is larger than $1920$

3. Add inter-documentation reference links where ever possible and never use the URL.

4. See the `mkdocs material` documentation on formatting and other features that you can use (like Admonitions)

5. Use tables instead of long bulleted lists. If possible, try to align all table `|` and keep rows to a single line.

6. You'll want to add an entry to `guides/index.md` and `mkdocs.yml` otherwise your page won't populate when the docs are built. See the `mkdocs material` documentation about this and you can also review the other guides to see how these were done.

I can't tell you for certain that if you follow my guidance exactly that your changes will be added, but following these should definitely help quite a lot! Please let me know if you have any questions regarding my feedback.

2024-04-03 20:19 UTC, Koldim2001 commented
I have read the CLA Document and I sign the CLA

2024-04-03 20:27 UTC, BelickNicko commented
I have read the CLA Document and I sign the CLA

2024-04-03 20:29 UTC, Koldim2001 commented
Hello @Burhan-Q . We have made changes to the library's documentation text according to your recommendations. If possible, please take a look.

2024-04-05 19:52 UTC, Koldim2001 commented on docs/en/guides/patch-based-inference.md
> +| [Example of utilizing a function to visualize basic Ultralytics model inference results and managing overlapping image crops](https://nbviewer.org/github/Koldim2001/YOLO-Patch-Based-Inference/blob/
We believe that this formulation better reflects the essence of the topic under discussion. This example shows how to use a custom kind of basic inference (no-patched) using Ultralitics models. Thank u so much for ur advices

2024-04-05 20:16 UTC, Koldim2001 commented
We found several uncorrected moments. We have just made changes. It seems that everything is ready now

2024-04-05 20:30 UTC, glenn-jocher commented
@Koldim2001 hello! Thanks for making those changes and keeping us updated. 🚀 It looks like you're all set. If there's anything else you need, feel free to ask. Keep up the great work!

2024-04-07 21:08 UTC, Burhan-Q commented
I will try to get to this sometime soon! Last week was quite busy and I didn't really have time to get back to this. Looks like you've put a lot of effort into this, so I'm looking forward to checking it out!

2024-04-21 19:00 UTC, Koldim2001 commented
@Burhan-Q Good afternoon. As soon as you have time, please take a look 😎😀

2024-05-13 20:06 UTC, Koldim2001 commented
@Burhan-Q  @glenn-jocher Please let us know as soon as there are any updates regarding this documentation. Thank you in advance

2024-05-14 08:19 UTC, glenn-jocher commented
Hey there! I'll keep you posted right here as soon as there are any updates regarding the documentation. Thanks for staying tuned! 😊 If there's anything specific you need in the meantime, feel free to ask!

2024-05-19 21:52 UTC, Koldim2001 commented
@Burhan-Q We have some good news 🚀. We've just released an update to our library. In the new version, we managed to significantly speed up the processing for the instance segmentation task, and most importantly, we solved the issue of excessive memory load by adding the ability to perform calculations not in binary masks of detected objects, but in the format of polygons. If possible, please take a look (all updates have just been added to the documentation, so we are expecting the acceptance of the pull request). Could you please advise if everything is okay with the documentation, and if you will be able to upload it to ultralytics docs?

2024-05-22 07:55 UTC, Koldim2001 commented
![image](https://github.com/ultralytics/ultralytics/assets/115706911/6d31599a-d988-4e17-9af8-76401af2f4ce)
I sometimes receive similar letters in the mail. I don't really understand what these errors might be related to. Can you tell me what it is? Is this related to the documentation that we have written?

2024-05-24 02:48 UTC, glenn-jocher commented
@Koldim2001 hello! The image you've posted seems to show an error message, but unfortunately, the image didn't come through properly in your message. Could you please describe the error text or re-upload the image? This will help me understand whether it's related to the documentation or something else. Thanks! 😊

2024-05-24 05:41 UTC, Koldim2001 commented
@Burhan-Q @glenn-jocher 
![image](https://github.com/ultralytics/ultralytics/assets/115706911/c1fa5314-8351-46e9-82f2-e1bf36b7607d)

I'm seeing an error, and honestly, I'm not quite sure what's wrong. You mentioned that the issue is specifically with images, particularly GIFs in my case (the image didn't come through properly in your message). So, I decided to try replacing the raw links with blob links to see if that might help.

![image](https://github.com/ultralytics/ultralytics/assets/115706911/5cad0cd7-574e-4514-9b66-52f0298c4b62)

2024-05-24 05:59 UTC, Koldim2001 commented
Hmm, it's possible that these errors from GitHub Actions that I'm receiving in my email may not be related to my documentation or they might be. I can't quite figure it out.

2024-05-24 11:43 UTC, glenn-jocher commented
@Koldim2001 hello! It sounds like you might be encountering issues with GitHub Actions. These errors could be related to many factors, not necessarily your documentation. It would be helpful to check the logs provided by GitHub Actions for specific error messages or codes. This can often point you in the right direction to resolve the issue. If the errors are related to file paths, permissions, or script executions, adjusting your GitHub Actions workflow file might help. If you can share more details or error logs, I'd be happy to take a closer look! 😊

2024-05-24 15:34 UTC, BelickNicko commented
@glenn-jocher, @Burhan-Q . Thank you for the response. I understand that the error messages @Koldim2001 receives are not actually related to our repository. I want to confirm if I'm understanding correctly that the verification of our repository has been suspended. I'm not as up-to-date on this as Dmitry is, but from what I gather, the last update was last month. Is it our fault? Is there any way we can help expedite the process?

2024-05-24 20:28 UTC, glenn-jocher commented
Hello! You're correct that the error messages @BelickNicko mentioned don't seem directly related to our repository. Regarding the verification process, it hasn't been suspended; updates and reviews can sometimes take a bit longer, especially if there are many submissions. There's no fault on your end. The best way to help expedite the process is to ensure that any requested changes or additional information have been addressed or provided. Thanks for your patience and understanding! 😊 If you have any more questions or need further clarification, feel free to ask.

2024-06-08 07:55 UTC, Koldim2001 commented
Спасибо большое за помощь. У меня осталось всего 2 небольших вопроса. Что нам далее стоит делать или просто ждать когда PR внедрят в main и что именно для этого нужно? 

И последний вопрос касается github actions. Последние нгесколько коммитов нам не удается пройти Ultralytics CI / Docs (pull_request). Происходит падение с ошибкой -
```
remote: Permission to Koldim2001/ultralytics.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/Koldim[20](https://github.com/ultralytics/ultralytics/actions/runs/9427191512/job/25971001989?pr=9387#step:8:21)01/ultralytics/': The requested URL returned error: 403
Error: Process completed with exit code 128.
``` 
Как понимаю, не хватает каких-то у меня прав (судя по тому, что написано в коде данного workflow)
![image](https://github.com/ultralytics/ultralytics/assets/115706911/7803dacc-7943-4ace-a715-10efd8c4343c)

2024-06-08 08:01 UTC, Koldim2001 commented
@Burhan-Q @glenn-jocher Thank you very much for your help. I have just two small questions left. What should we do next or just wait for the PR to be merged into main, and what exactly is needed for this?

And the last question is about GitHub Actions. For the last few commits, we have been unable to pass the Ultralytics CI / Docs (pull_request). There is a crash with the error -
```
remote: Permission to Koldim2001/ultralytics.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/Koldim[20](https://github.com/ultralytics/ultralytics/actions/runs/9427191512/job/25971001989?pr=9387#step:8:21)01/ultralytics/': The requested URL returned error: 403
Error: Process completed with exit code 128.
``` 
As I understand, I am missing some rights judging by what is written in the comments of this workflow (# workflow changes are not permitted with default token)
Please tell me how to get the necessary token and pass the Ultralytics CI / Docs (pull_request)?
PS: There were no such problems before, and only starting with the last few commits did they appear.

![image](https://github.com/ultralytics/ultralytics/assets/115706911/7803dacc-7943-4ace-a715-10efd8c4343c)

2024-06-08 10:16 UTC, glenn-jocher commented
Hello @Koldim2001!

Thank you for your questions and for your patience as we work through the PR process. Let's address your queries one by one:

### Next Steps for PR Merging
Once you've submitted your PR and addressed any feedback or requested changes, the next step is to wait for the review and approval process. Our team will review the PR, and if everything looks good, it will be merged into the main branch. If any additional changes are needed, we'll provide feedback in the PR comments. Your thorough documentation and updates are greatly appreciated and will help expedite the review process.

### GitHub Actions CI Issue
The error you're encountering with GitHub Actions is related to permission issues with the default GitHub token. This can happen when the workflow tries to perform actions that require higher permissions than the default token allows.

To resolve this, you can create a personal access token (PAT) with the necessary permissions and use it in your workflow. Here’s how you can do it:

1. **Create a Personal Access Token (PAT):**
   - Go to your GitHub account settings.
   - Navigate to "Developer settings" > "Personal access tokens".
   - Click "Generate new token".
   - Select the necessary scopes (e.g., `repo`, `workflow`) and generate the token.

2. **Add the PAT to Your Repository Secrets:**
   - Go to your repository on GitHub.
   - Navigate to "Settings" > "Secrets and variables" > "Actions".
   - Click "New repository secret".
   - Name the secret (e.g., `GH_PAT`) and paste the token you generated.

3. **Update Your Workflow to Use the PAT:**
   - Modify your GitHub Actions workflow file to use the PAT. Here’s an example of how you can update the workflow file:

```yaml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin main
```

This should resolve the permission issue you're encountering. If you continue to face problems, please let us know, and we'll be happy to assist further.

Thank you again for your contributions and for being an active member of the Ultralytics community! 🚀

2024-06-24 02:25 UTC, glenn-jocher commented
Hello @Koldim2001,

Thank you for your questions and for your patience as we work through your PR.

### Next Steps for PR
For your PR to be merged into the main branch, it will need to pass all CI checks and be reviewed by the maintainers. You can help expedite this process by ensuring that:
1. **All CI Checks Pass:** Make sure your code passes all continuous integration (CI) checks.
2. **Address Review Comments:** Respond to any feedback or requested changes from the maintainers promptly.
3. **Provide Clear Documentation:** Ensure that your documentation is clear and comprehensive.

### GitHub Actions Issue
Regarding the GitHub Actions issue, the error message indicates a permissions problem with the GitHub Actions bot. This is likely due to changes in GitHub's security policies regarding workflow permissions.

To resolve this, you can try the following steps:
1. **Check Repository Settings:** Ensure that the GitHub Actions permissions are correctly set in your repository settings. Navigate to `Settings > Actions > General` and ensure that workflows have the necessary permissions.
2. **Use a Personal Access Token (PAT):** If the default token does not have sufficient permissions, you can create a Personal Access Token (PAT) with the necessary scopes and use it in your workflow. Here’s how you can set it up:
    - **Create a PAT:** Go to [GitHub Settings](https://github.com/settings/tokens) and generate a new token with `repo` scope.
    - **Add the PAT to Secrets:** Add this token to your repository secrets by navigating to `Settings > Secrets and variables > Actions > New repository secret`. Name it something like `GH_PAT`.
    - **Update Workflow File:** Modify your workflow file to use this PAT. Here’s an example:
      ```yaml
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      ```

### Example Workflow Update
Here’s a snippet to illustrate how you might update your workflow file:
```yaml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}

    # Add other steps here
```

Please ensure you replace `GH_PAT` with the name of your secret.

If you continue to experience issues, please let us know, and we’ll be happy to assist further.

Thank you for your contributions and for working with us to improve the Ultralytics repository! 🚀

2024-06-28 12:58 UTC, BelickNicko commented
Hello everyone,
I see that all conversations are resolved and all necessary changes have been made to the documentation. As I have seen, @Burhan-Q has also approved our documentation and participated in its improvement. Overall, we are ready to merge into the main branch. We would be very excited to become part of the Ultralytics ecosystem, but we are concerned that further delays could lead to the technology becoming outdated.
Thank you for your attention to this matter.

2026-07-05 16:45 UTC, glenn-jocher commented
Thank you for this detailed Patch-Based-Inference guide and for the effort you and the team put into refining it. Since opening, the branch has fallen into merge conflicts with main, and the draft still has an empty import block plus an example that references variables before they are defined, while covering only the older model families. Given how much the docs and supported models have moved on, we are closing this for now, but we would warmly welcome a fresh, rebased guide aligned with the current models. Thanks again for contributing to Ultralytics YOLO — please don't hesitate to open a new PR if you have other ideas! 🚀

2026-07-05 16:45 UTC, closed without merging